### ISSUE TITLE
Required entries don't show up in generated maps

### ISSUE THREAD

**Issue by respatialized** [green-coder/minimallist#12]
I previously reported this issue in the #minimallist channel on the Clojurians slack.

> I'm facing an issue when I'm trying to generate map data with some required keys and some optional keys. Here's what reproduces the issue for me:
> 
> ```clojure
> (require '[minimallist.helper :as h])
> (require '[clojure.test.check.generators :as gen])(-> (h/map)
>       (h/with-optional-entries [:str (-> (h/fn string?)
>                                          (h/with-test-check-gen gen/string-ascii))])
>       (h/with-entries [:int (-> (h/fn int?)
>                                 (h/with-test-check-gen gen/nat))])
>       mg/gen
>       (gen/sample 20))
> ```
> 
> A few samples show plenty of results that have the :str key without the :int key. What I expect (at least sometimes) to see is the reverse: maps that have the :int key but not the :str key. But I don't:
> ```clojure
> (-> (h/map)
>       (h/with-optional-entries [:str (-> (h/fn string?)
>                                          (h/with-test-check-gen gen/string-ascii))])
>       (h/with-entries [:int (-> (h/fn int?)
>                                 (h/with-test-check-gen gen/nat))])
>       mg/gen
>       (gen/sample 2000)
>       (#(filter (fn [m] (and (contains? m :int)
>                              (not (contains? m :str)))) %)))
> ```
> This always returns an empty list, regardless of sample size.

**Comment by respatialized** [comment]
I previously attempted to diagnose the issue by reading through the source code:

> https://github.com/green-coder/minimallist/blob/1469349924c766c3aeb033e8f7016f8429e4af69/src/minimallist/generator.cljc#L424
> It looks like this may be part of the reason for why I'm seeing what I'm seeing. There don't appear to be any guarantees that all the required-entries appear in selected-entries after the collection is shuffled, so those entries may not show up in the collection built up by the call to mapcat at the end of this expression.
> Of course, this is my first time reading through the code, so it may not be as simple as I think.

As I suspected, the issue may be a bit murkier than I originally anticipated. I have a branch that extends the test cases to reproduce the issue I observe. Here's the diff:
https://github.com/green-coder/minimallist/compare/all-work-and-no-play...respatialized:optional-map-gen-bugfix

I extended one of the existing test cases to add an expression checking the property I wanted to check: 
> _a value generated by a model with required entry `:a` and optional entry `:b` contains `:a` but not `:b` at least once in a sample of generated data_

That test passes. But the additional test that I added, using the expression above, fails for the same property. 

I intend to compare the models built by those test expressions in the REPL to see what may account for the difference, but I wanted to report what I've found so far.

**Comment by green-coder** [comment]
Thanks a lot @respatialized  for your bug report and your PR. 👍

**Comment by respatialized** [comment]
@green-coder You're quite welcome! Glad I could contribute.
